-- CREATE INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION WALMART_PROJECT_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'enter_your arn:aws:iam::'
  STORAGE_ALLOWED_LOCATIONS = ('enter your s3 storage location');

-- CREATE TRUST BTW WITH AWS ACCOUNT AND SNOWFLAKE ACCOUNT
-- GET REQUIRED INFORMATION
-- DESC INTEGRATION WALMART_PROJECT_INT;



-- LIST THE CONTENT OF THE S3 BUCKET TO TEST THE INTEGRATION IS WORKING
-- LS @WALMART_PROJECT_DB.BRONZE.WALMART_PROJECT_STAGE