-- CREATE AN EXTERNAL STAGE TO ACCES THE FILES IN S3
CREATE OR REPLACE STAGE WALMART_PROJECT_DB.BRONZE.WALMART_PROJECT_STAGE
STORAGE_INTEGRATION = WALMART_PROJECT_INT
URL= 's3://ola-e2e-walmart-project-data-bucket/data/';


-- LIST THE CONTENT OF THE S3 BUCKET TO TEST THE INTEGRATION IS WORKING
LS @WALMART_PROJECT_DB.BRONZE.WALMART_PROJECT_STAGE