CREATE OR REPLACE TABLE WALMART_PROJECT_DB.BRONZE.DEPARTMENT_COPY
(
    STORE INT NOT NULL,
    DEPT INT NOT NULL,
    DATE TIMESTAMP_NTZ(6) NOT NULL,
    WEEKLY_SALES DECIMAL,
    ISHOLIDAY VARCHAR()
    -- INSERT_DATE TIMESTAMP,
   --  UPDATE_DATE TIMESTAMP
);
SELECT * FROM DEPARTMENT_COPY;

CREATE OR REPLACE TABLE WALMART_PROJECT_DB.BRONZE.STORE_COPY
(
    STORE INT NOT NULL,
    TYPE VARCHAR() NOT NULL COLLATE 'en-ci',
    SIZE INT
    -- INSERT_DATE TIMESTAMP,
    -- UPDATE_DATE TIMESTAMP
);


CREATE OR REPLACE TABLE WALMART_PROJECT_DB.BRONZE.FACT_COPY
(
    STORE INT NOT NULL,
    DATE TIMESTAMP NOT NULL,
    TEMPERATURE INT,
    FUEL_PRICE DECIMAL,
    MARKDOWN1 DECIMAL,
    MARKDOWN2 DECIMAL,
    MARKDOWN3 DECIMAL,
    MARKDOWN4 DECIMAL,
    MARKDOWN5 DECIMAL,
    CPI DECIMAL,
    UNEMPLOYMENT DECIMAL,
    ISHOLIDAY VARCHAR()
    --VRSN_START_DATE TIMESTAMP,
    --VRSN_END_DATE TIMESTAMP,
    --INSERT_DATE TIMESTAMP,
    --UPDATE_DATE TIMESTAMP
);