CREATE OR REPLACE STREAM WALMART_PROJECT_DB.BRONZE.DEPARTMENT_STREAM
ON TABLE WALMART_PROJECT_DB.BRONZE.DEPARTMENT_COPY
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM WALMART_PROJECT_DB.BRONZE.STORE_STREAM
ON TABLE WALMART_PROJECT_DB.BRONZE.STORE_COPY
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM WALMART_PROJECT_DB.BRONZE.FACT_STREAM
ON TABLE WALMART_PROJECT_DB.BRONZE.FACT_COPY
APPEND_ONLY = TRUE;